# Generated by Django 4.1.4 on 2023-05-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypack',
            name='ref_id',
            field=models.IntegerField(default=0),
        ),
    ]
