# Generated by Django 4.1.4 on 2023-01-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='تهران', max_length=30),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(default='خانه', max_length=30),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='تهران', max_length=30),
        ),
    ]
