# Generated by Django 4.1.4 on 2023-01-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_delivery_man',
            field=models.BooleanField(default=False),
        ),
    ]
