# Generated by Django 4.1.4 on 2023-01-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='shop.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60)),
                ('image', models.ImageField(upload_to='static/shop/images')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('country_made', models.CharField(max_length=20)),
                ('exp_date', models.DateField()),
                ('pro_date', models.DateField()),
                ('category', models.ManyToManyField(related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
