# Generated by Django 4.1.4 on 2023-04-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_order_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_cost',
            field=models.IntegerField(default=0),
        ),
    ]
